/** Pricing packages, from two sources:
 *  - public/Website Packages.docx — the website packages and the $999 Elite
 *    Ecommerce Package
 *  - public/pricing-packages.txt — ecommerce, mobile app, branding, SEO and
 *    digital marketing packages (generated from the file by script)
 *
 *  Wording is the sources' own. Formatting marks became structure: a "Value
 *  Added Services" line splits `features` from `valueAdded`, asterisks around
 *  a closing line become `note`, and `**…**` marks bold runs (e.g. "FREE").
 *  Five obvious typos in the .txt were corrected: Gurantee, Sign age,
 *  Stationary, "repor" and "enture" (Venture).
 *
 *  `was` is the struck-through original price beside `price`. Packages with
 *  no price in the source (the mobile app plans) show "Custom Quote" instead.
 *  `period` replaces the word "Only" for recurring plans ("Per month"). */
export type Package = {
  name: string;
  price?: number;
  was?: number;
  period?: string;
  bestSeller?: boolean;
  features: string[];
  valueAddedLabel?: string;
  valueAdded?: string[];
  note?: string;
};

const VALUE_ADDED = [
  "Complete Source Files",
  "Dedicated Project Manager",
  "100% Ownership Rights",
  "100% Satisfaction Guarantee",
  "100% Money Back Guarantee",
];

const NOTE = "NO MONTHLY OR ANY HIDDEN FEE";

export const WEBSITE_PACKAGES: Package[] = [
  {
    name: "Basic Website Package",
    price: 99,
    was: 189,
    features: [
      "2 Page Website Design",
      "Custom Layout",
      "Contact Form",
      "1 Banner Design",
      "2 Stock Photos",
      "**FREE** Favicon Design",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
    ],
    valueAddedLabel: "Value Added Services",
    valueAdded: VALUE_ADDED,
    note: NOTE,
  },
  {
    name: "Startup Website Package",
    price: 299,
    was: 598,
    features: [
      "5 Page Website Design",
      "Custom Layout",
      "Contact Form",
      "3 Banner Designs",
      "5 Stock Photos (You can provide us more)",
      "**FREE** Favicon Design",
      "**FREE** Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design and Launch",
    ],
    valueAddedLabel: "Value Added Services",
    valueAdded: VALUE_ADDED,
    note: NOTE,
  },
  {
    name: "Professional Website Package",
    price: 499,
    was: 998,
    bestSeller: true,
    features: [
      "5 to 10 Unique Pages Website Design",
      "CMS Integration **(WordPress)**",
      "5+ Stock Photos & Banner Designs",
      "**FREE** Favicon Design",
      "**FREE** Social Media Integration",
      "**FREE** Google Friendly Sitemap",
      "Unlimited Revisions",
      "Complete W3C Certified HTML",
      "Initial Concepts in 48 Hours",
      "Complete Design & Launch",
      "Custom, Interactive & Dynamic Web Design",
      "Team of Expert Designers and Developers",
    ],
    valueAddedLabel: "Value Added Services",
    valueAdded: VALUE_ADDED,
    note: NOTE,
  },
  {
    name: "Corporate Website Package",
    price: 699,
    was: 1398,
    features: [
      "15 to 20 Unique Pages Website Design",
      "CMS Integration **(WordPress)**",
      "Mobile Friendly **Responsive**",
      "Custom, Interactive & Dynamic Design",
      "Customize WordPress Theme Development",
      "Interactive Sliding Banners",
      "10 Stock Images",
      "10 Banner Designs",
      "Unlimited Revisions",
      "**FREE** Favicon Design",
      "Social Media Integration",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "W3C Certified HTML",
      "Team of Award-Winning Designers and Developers",
    ],
    valueAddedLabel: "Value Added Services",
    valueAdded: VALUE_ADDED,
    note: NOTE,
  },
  {
    name: "Identity Website Package",
    price: 1399,
    was: 2798,
    features: [
      "Unlimited Web Pages",
      "Custom Made, Interactive, Dynamic & High End Design",
      "Customized WordPress & PHP Development",
      "Interactive Sliding Banners",
      "Up to 15 Custom Made Banner Designs",
      "15 Stock Images",
      "Unlimited Revisions",
      "Content Management System",
      "Optional Online Appointment/Booking Integration",
      "Online Payment Integration (Optional)",
      "Optional Multi-Lingual Support",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional)",
      "Mobile Responsive",
      "Up to 15 Professional Email ID’s",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "W3C Certified HTML",
      "Team of Award-Winning Designers and Developers",
    ],
    valueAddedLabel: "Value Added Services",
    valueAdded: VALUE_ADDED,
    note: NOTE,
  },
];

/** The document's ecommerce package, shown under the Ecommerce tab rather
 *  than alongside the website packages. */
export const ECOMMERCE_PACKAGES: Package[] = [
  {
    name: "Elite Ecommerce Package",
    price: 999,
    was: 1998,
    features: [
      "Custom Ecommerce Website Design",
      "Unlimited Products",
      "CMS Integration **(WordPress)**",
      "Fully **Mobile Responsive**",
      "**Shopping Cart** Integration",
      "**Payment Gateway** Integration",
      "Product Listing & Management",
      "Order Management & Tracking",
      "Banner Designs",
      "Unlimited Revisions",
      "**FREE** Favicon Design",
      "Social Media Integration",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "W3C Certified HTML",
      "Team of Expert Designers and Developers",
    ],
    valueAddedLabel: "Value-Added Services:",
    valueAdded: VALUE_ADDED,
    note: NOTE,
  },
];

/* ---------- From public/pricing-packages.txt ---------- */

const ECOMMERCE_EXTRA: Package[] = [
  {
    name: "Corporate E-commerce Package",
    price: 1589,
    was: 3178,
    features: [
      "Up-to 15 Unique Pages Website",
      "Up-to 500 Products",
      "Conceptual and Dynamic Website",
      "Easy Product Search",
      "Product Reviews",
      "Content Management System (CMS)",
      "Mobile Responsive",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Sales & Inventory Management",
      "Jquery Slider",
      "Free Google Friendly Sitemap",
      "Custom Email Addresses",
      "Complete W3C Certified HTML",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Elite E-commerce Package",
    price: 2699,
    was: 5398,
    features: [
      "Unlimited Pages Website",
      "E-Commerce Store Design",
      "Product Detail Page Design",
      "Unlimited Products",
      "Unlimited Categories",
      "Product Rating & Reviews",
      "Unique Banner Slider",
      "Featured Products Showcase",
      "Full Shopping Cart Integration",
      "Multi-currency Support",
      "Online Payment Module Setup",
      "Facebook Shop Integration",
      "Sales & Inventory Management",
      "Easy Product Search",
      "Payment Gateway Integration",
      "Content Management System/CMS",
      "Customer Log-in Area",
      "Mobile Responsive",
      "Social Media Plugins Integration",
      "Tell a Friend Feature",
      "Social Media Pages",
    ],
    valueAddedLabel: "Value Added Services",
    valueAdded: [
      "**FREE** Custom Logo Design",
      "**FREE** Icon Design",
      "**FREE** Print Media",
      "**FREE** Stationery Design (Business Card, Letterhead & Envelope Design)",
      "**FREE** Invoice Design",
      "**FREE** Bi-Fold Brochure (OR) 2-Sided Flyer Design",
      "**FREE** Product Catalog Design",
      "**FREE** Signage Design (OR) Label Design",
      "**FREE** T-Shirt Design (OR) Car Wrap Design",
      "**FREE** Email Signature Design",
      "**FREE** Facebook, Twitter, YouTube, Google+ & Pinterest Page Designs",
      "Dedicated Account Manager",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
    note: "NO MONTHLY OR ANY HIDDEN FEE",
  },
];

const MOBILE_APP_PACKAGES: Package[] = [
  {
    name: "Basic Plan",
    features: [
      "50% Upfront to get started with the work immediately",
      "Wireframing",
      "Intuitive UI UX (Custom App Design)",
      "Social Media Integration",
      "App Testing",
      "Native iOS OR Android app",
      "Paid bug support ($350/m)",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Pro Plan",
    features: [
      "50% Upfront to get started with the work immediately",
      "Wireframing",
      "Intuitive UI UX (Custom App Design)",
      "Social Media Integration",
      "App Testing",
      "Ads Network Integration",
      "Firebase Integration",
      "In-App Purchase",
      "Publishing on App Store",
      "1 Month free bug support",
      "Native iOS OR Android app",
      "Cross-Platform (Hybrid) On Demand",
      "Push Notifications",
      "Messaging API Integration (Live Chat)",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Business Plan",
    features: [
      "50% Upfront to get started with the work immediately",
      "Wireframing",
      "Intuitive UI UX (Custom App Design)",
      "Social Media Integration",
      "App Testing",
      "Ads Network Integration",
      "Firebase Integration",
      "In-App Purchase",
      "Publishing on App Store",
      "App Store Optimization",
      "3 Month free bug support",
      "Native iOS OR Android app",
      "Cross-Platform (Hybrid) On Demand",
      "Push Notifications",
      "Messaging API Integration (Live Chat)",
      "Regular App Updates Yearly 1 Update",
      "Google Maps Integration",
      "Admin Panel",
      "Data Import/Export",
      "Web APIs and Online Database",
      "Picture Gallery/Product Display/Showcase Services On Demand",
      "Product Categories/Sub Categories",
      "CrashAnalytics Integration",
      "Audio/Video Streaming",
      "Payment Gateways Integration",
      "Shopping Cart",
      "3rd Party APIs Integrations",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
];

const BRANDING_PACKAGES: Package[] = [
  {
    name: "Startup Plan",
    price: 60,
    was: 120,
    features: [
      "Business Card Design",
      "Letterhead Design",
      "Envelope Design",
      "24/7 Customer Support",
      "100% Ownership",
      "100% Unique Design Guarantee",
      "100% Money-Back Guarantee",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    name: "Professional Plan",
    price: 100,
    was: 200,
    features: [
      "Business Card Design",
      "Letterhead Design",
      "Envelope Design",
      "Email Signature",
      "2 Social Covers",
      "24/7 Customer Support",
      "100% Ownership",
      "100% Unique Design Guarantee",
      "100% Money-Back Guarantee",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    name: "Ultimate Plan",
    price: 200,
    was: 400,
    features: [
      "Business Card Design",
      "Letterhead Design",
      "Envelope Design",
      "Email Signature",
      "4 Social Covers",
      "T-Shirt Design",
      "Web Banner Design",
      "Signage Design",
      "Car Stickers Design",
      "24/7 Customer Support",
      "100% Ownership",
      "100% Unique Design Guarantee",
      "100% Money-Back Guarantee",
      "100% Satisfaction Guarantee",
    ],
  },
];

const SEO_PACKAGES: Package[] = [
  {
    name: "Basic SEO Plan",
    price: 1199,
    was: 2398,
    period: "Per month",
    features: [
      "Local Business Listings",
      "Blog Content Creation",
      "Local SEO Deployment",
      "15 Selected Keywords Targeting",
      "15 Pages Keyword Targeted",
      "Prior & Business Assessment",
      "Consumer & Competitor Assessment",
      "Webpage Optimization",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of Anchors Tags",
      "Inclusion of Anchors Indexing Modifications",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ's Integration",
      "Link Building",
      "Meta Tags Creation",
      "Tracking & Analysis",
      "Google Places Inclusions",
      "Google Analytics & Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Monthly Reporting",
      "Off Page Optimization",
      "Directory Submission",
      "Email & Phone Support",
    ],
  },
  {
    name: "Gold SEO Plan",
    price: 1599,
    was: 3198,
    period: "Per month",
    features: [
      "Local Business Listings",
      "Blog Content Creation",
      "Local SEO Deployment",
      "30 Selected Keywords Targeting",
      "30 Pages Keyword Targeted",
      "Prior & Business Assessment",
      "Consumer & Competitor Assessment",
      "Webpage Optimization",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of Anchors Tags",
      "Inclusion of Anchors Indexing Modifications",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ's Integration",
      "Link Building",
      "Meta Tags Creation",
      "Tracking & Analysis",
      "Google Places Inclusions",
      "Google Analytics & Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Monthly Reporting",
      "Off Page Optimization",
      "Directory Submission",
      "Email & Phone Support",
    ],
  },
  {
    name: "Platinum SEO Plan",
    price: 2200,
    was: 4400,
    period: "Per month",
    features: [
      "Local Business Listings",
      "Blog Content Creation",
      "Local SEO Deployment",
      "70 Selected Keywords Targeting",
      "70 Pages Keyword Targeted",
      "Prior & Business Assessment",
      "Consumer & Competitor Assessment",
      "Webpage Optimization",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of Anchors Tags",
      "Inclusion of Anchors Indexing Modifications",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ's Integration",
      "Link Building",
      "Meta Tags Creation",
      "Tracking & Analysis",
      "Google Places Inclusions",
      "Google Analytics & Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Monthly Reporting",
      "Off Page Optimization",
      "Directory Submission",
      "Email & Phone Support",
    ],
  },
];

const DIGITAL_MARKETING_PACKAGES: Package[] = [
  {
    name: "Startup SMM Plan",
    price: 349,
    was: 698,
    period: "Per month",
    features: [
      "3 postings per week (per network) Facebook + Twitter + Instagram + Google+",
      "Content Creation",
      "Business Page Optimization",
      "Social Media Strategy (Overview)",
      "Facebook Likes Campaign",
      "Monthly Progress report",
      "Copy Writing",
    ],
  },
  {
    name: "Scaling SMM Plan",
    price: 699,
    was: 1398,
    period: "Per month",
    features: [
      "5 postings per week (per network) Facebook + Twitter + Instagram + Google+",
      "Copywriting & Visual designs",
      "Business Page Optimization",
      "Ad Campaign Management",
      "Spam monitoring",
      "Monthly Progress report",
    ],
  },
  {
    name: "Venture SMM Plan",
    price: 1199,
    was: 2389,
    period: "Per month",
    features: [
      "6 postings per week (per network) Facebook + Twitter + Instagram + Google+",
      "Copywriting & Visual designs",
      "Business Page Optimization",
      "Ad Campaign Management",
      "Spam monitoring",
      "Reputation Management",
      "Social Account Setup",
      "Content Creation",
      "Social Media Hearing",
      "Query and comments reply",
    ],
  },
];

/** Packages per pricing tab. Tabs without packages show a custom-quote
 *  prompt. */
export const PACKAGES_BY_CATEGORY: Record<string, Package[]> = {
  "Web Development": WEBSITE_PACKAGES,
  Ecommerce: [...ECOMMERCE_PACKAGES, ...ECOMMERCE_EXTRA],
  "Mobile Apps": MOBILE_APP_PACKAGES,
  SEO: SEO_PACKAGES,
  Branding: BRANDING_PACKAGES,
  "Digital Marketing": DIGITAL_MARKETING_PACKAGES,
};
